namespace HrDecisionSupport.Application.EmployeeImports.Spreadsheet;

public sealed record EmployeeImportSourceRow(
    int SourceRowNumber,
    string? AnonymousEmployeeCode,
    string? CurrentPosition,
    decimal? TotalExperienceYears,
    decimal? BackendExperienceYears,
    string? PreviousPositionsRaw,
    string? TechnicalSkillsRaw,
    string? TechnologiesAndToolsRaw,
    string? ProjectExperiencesRaw,
    string? SectorExperienceRaw,
    string? EducationLevelRaw,
    string? EducationFieldRaw,
    string? CertificatesRaw,
    string? ForeignLanguagesRaw,
    string? WorkModeExperienceRaw,
    DateOnly? HireDate,
    DateOnly? TerminationDate,
    decimal? CompanyTenureYears,
    decimal? PreviousCompanyAverageStayMonths,
    int? ShortestPreviousJobMonths,
    int? LongestPreviousJobMonths,
    int? LastPreviousCompanyStayMonths,
    int? CompanyChangeCount,
    decimal? JobChangeRate,
    int? StayLabel,
    IReadOnlyDictionary<string, string?> RawValues,
    IReadOnlyList<EmployeeImportDiagnostic> Diagnostics);
