<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HrDecisionSupport.Domain\HrDecisionSupport.Domain.csproj" />
    <ProjectReference Include="..\HrDecisionSupport.Application\HrDecisionSupport.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
