// <auto-generated />
using System;
using HrDecisionSupport.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace HrDecisionSupport.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrDecisionSupportDbContext))]
    [Migration("20260818114227_AddPersistentJobMatchingHistory")]
    partial class AddPersistentJobMatchingHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AvailabilityDays")
                        .HasColumnType("integer")
                        .HasColumnName("availability_days");

                    b.Property<string>("CandidateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("candidate_code");

                    b.Property<int>("CandidateSource")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_source");

                    b.Property<string>("ExternalCandidateId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_candidate_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("ProfessionalTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("professional_title");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCode")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("candidates", null, t =>
                        {
                            t.HasCheckConstraint("ck_candidates_availability_days_non_negative", "availability_days IS NULL OR availability_days >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateCareerFeatureSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BackendExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("backend_experience_months");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<int?>("CompanyChangeCount")
                        .HasColumnType("integer")
                        .HasColumnName("company_change_count");

                    b.Property<string>("FeatureSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feature_schema_version");

                    b.Property<decimal?>("JobChangeRate")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("job_change_rate");

                    b.Property<int?>("LastPreviousCompanyStayMonths")
                        .HasColumnType("integer")
                        .HasColumnName("last_previous_company_stay_months");

                    b.Property<int?>("LongestPreviousJobMonths")
                        .HasColumnType("integer")
                        .HasColumnName("longest_previous_job_months");

                    b.Property<decimal?>("PreviousCompanyAverageStayMonths")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("previous_company_average_stay_months");

                    b.Property<int?>("ShortestPreviousJobMonths")
                        .HasColumnType("integer")
                        .HasColumnName("shortest_previous_job_months");

                    b.Property<int?>("TotalExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("total_experience_months");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "FeatureSchemaVersion")
                        .IsUnique();

                    b.ToTable("candidate_career_feature_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_candidate_career_feature_snapshots_non_negative", "(total_experience_months IS NULL OR total_experience_months >= 0) AND (backend_experience_months IS NULL OR backend_experience_months >= 0) AND (previous_company_average_stay_months IS NULL OR previous_company_average_stay_months >= 0) AND (shortest_previous_job_months IS NULL OR shortest_previous_job_months >= 0) AND (longest_previous_job_months IS NULL OR longest_previous_job_months >= 0) AND (last_previous_company_stay_months IS NULL OR last_previous_company_stay_months >= 0) AND (company_change_count IS NULL OR company_change_count >= 0) AND (job_change_rate IS NULL OR job_change_rate >= 0)");

                            t.HasCheckConstraint("ck_candidate_feature_backend_lte_total", "backend_experience_months IS NULL OR total_experience_months IS NULL OR backend_experience_months <= total_experience_months");

                            t.HasCheckConstraint("ck_candidate_feature_shortest_lte_longest", "shortest_previous_job_months IS NULL OR longest_previous_job_months IS NULL OR shortest_previous_job_months <= longest_previous_job_months");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateEvaluationCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("JobRequisitionId");

                    b.HasIndex("CandidateId", "JobRequisitionId")
                        .IsUnique();

                    b.ToTable("candidate_evaluation_cases", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateWorkModePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<Guid>("WorkModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_mode_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkModeId");

                    b.HasIndex("CandidateId", "WorkModeId")
                        .IsUnique();

                    b.ToTable("candidate_work_mode_preferences", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Issuer")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("CompetencyCategory")
                        .HasColumnType("integer")
                        .HasColumnName("competency_category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("competencies", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EducationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DegreeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("degree_level");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_of_study");

                    b.Property<DateOnly?>("GraduationDate")
                        .HasColumnType("date")
                        .HasColumnName("graduation_date");

                    b.Property<string>("Institution")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("institution");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("education_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_education_records_graduation_date_not_before_start_date", "start_date IS NULL OR graduation_date IS NULL OR graduation_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("employment_status");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("termination_date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("employees", null, t =>
                        {
                            t.HasCheckConstraint("ck_employees_termination_date_not_before_hire_date", "termination_date IS NULL OR termination_date >= hire_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PositionId");

                    b.ToTable("employee_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_assignments_end_date_not_before_start_date", "start_date IS NULL OR end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeCareerFeatureSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BackendExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("backend_experience_months");

                    b.Property<int?>("CompanyChangeCount")
                        .HasColumnType("integer")
                        .HasColumnName("company_change_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FeatureSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feature_schema_version");

                    b.Property<int>("FeatureSource")
                        .HasColumnType("integer")
                        .HasColumnName("feature_source");

                    b.Property<bool?>("HasPreviousCompany")
                        .HasColumnType("boolean")
                        .HasColumnName("has_previous_company");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<decimal?>("ImportedJobChangeRate")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("imported_job_change_rate");

                    b.Property<int?>("LastPreviousCompanyStayMonths")
                        .HasColumnType("integer")
                        .HasColumnName("last_previous_company_stay_months");

                    b.Property<int?>("LongestPreviousJobMonths")
                        .HasColumnType("integer")
                        .HasColumnName("longest_previous_job_months");

                    b.Property<DateOnly?>("ObservedAt")
                        .HasColumnType("date")
                        .HasColumnName("observed_at");

                    b.Property<int?>("ObservedCompanyTenureMonths")
                        .HasColumnType("integer")
                        .HasColumnName("observed_company_tenure_months");

                    b.Property<decimal?>("PreviousCompanyAverageStayMonths")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("previous_company_average_stay_months");

                    b.Property<int?>("ShortestPreviousJobMonths")
                        .HasColumnType("integer")
                        .HasColumnName("shortest_previous_job_months");

                    b.Property<int?>("TotalExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("total_experience_months");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("EmployeeId", "ImportBatchId", "FeatureSchemaVersion")
                        .IsUnique();

                    b.ToTable("employee_career_feature_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_emp_feature_backend_lte_total", "backend_experience_months IS NULL OR total_experience_months IS NULL OR backend_experience_months <= total_experience_months");

                            t.HasCheckConstraint("ck_emp_feature_job_change_rate_non_negative", "imported_job_change_rate IS NULL OR imported_job_change_rate >= 0");

                            t.HasCheckConstraint("ck_emp_feature_shortest_lte_longest", "shortest_previous_job_months IS NULL OR longest_previous_job_months IS NULL OR shortest_previous_job_months <= longest_previous_job_months");

                            t.HasCheckConstraint("ck_employee_career_feature_snapshots_months_non_negative", "(total_experience_months IS NULL OR total_experience_months >= 0) AND (backend_experience_months IS NULL OR backend_experience_months >= 0) AND (previous_company_average_stay_months IS NULL OR previous_company_average_stay_months >= 0) AND (shortest_previous_job_months IS NULL OR shortest_previous_job_months >= 0) AND (longest_previous_job_months IS NULL OR longest_previous_job_months >= 0) AND (last_previous_company_stay_months IS NULL OR last_previous_company_stay_months >= 0) AND (company_change_count IS NULL OR company_change_count >= 0) AND (observed_company_tenure_months IS NULL OR observed_company_tenure_months >= 0)");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DatasetSplit")
                        .HasColumnType("integer")
                        .HasColumnName("dataset_split");

                    b.Property<int>("FailedRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_row_count");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<DateOnly?>("ObservationDate")
                        .HasColumnType("date")
                        .HasColumnName("observation_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfulRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("successful_row_count");

                    b.Property<int>("TotalRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_row_count");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.ToTable("employee_import_batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_emp_import_batch_completed_counts_lte_total", "successful_row_count + failed_row_count <= total_row_count");

                            t.HasCheckConstraint("ck_employee_import_batches_file_hash_lowercase_sha256", "file_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_employee_import_batches_row_counts_non_negative", "total_row_count >= 0 AND successful_row_count >= 0 AND failed_row_count >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("ExternalEmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_employee_code");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("integer")
                        .HasColumnName("import_status");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload_json");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("source_row_number");

                    b.Property<string>("ValidationErrorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_errors_json");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ImportBatchId", "ExternalEmployeeCode")
                        .IsUnique()
                        .HasFilter("\"external_employee_code\" IS NOT NULL");

                    b.HasIndex("ImportBatchId", "SourceRowNumber")
                        .IsUnique();

                    b.ToTable("employee_import_rows", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_import_rows_source_row_number_positive", "source_row_number > 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeRetentionLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EmployeeCareerFeatureSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_career_feature_snapshot_id");

                    b.Property<int>("Label")
                        .HasColumnType("integer")
                        .HasColumnName("label");

                    b.Property<string>("LabelDefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_definition_version");

                    b.Property<int>("LabelSource")
                        .HasColumnType("integer")
                        .HasColumnName("label_source");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCareerFeatureSnapshotId")
                        .IsUnique();

                    b.ToTable("employee_retention_labels", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_retention_labels_label_valid", "label IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmploymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employer_name");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position_title");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("employment_histories", null, t =>
                        {
                            t.HasCheckConstraint("ck_employment_histories_end_date_not_before_start_date", "end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobLanguageRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("HardFilterEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("hard_filter_enabled");

                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<int>("MinimumProficiency")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_proficiency");

                    b.HasKey("Id");

                    b.HasIndex("JobRequisitionId");

                    b.HasIndex("LanguageId");

                    b.ToTable("job_language_requirements", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobMatchingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CandidatePoolCount")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_pool_count");

                    b.Property<string>("ConfigurationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_snapshot_json");

                    b.Property<string>("EmbeddingModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("embedding_model_name");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<int>("FinalCandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("final_candidate_count");

                    b.Property<int>("FinalTopN")
                        .HasColumnType("integer")
                        .HasColumnName("final_top_n");

                    b.Property<int>("HardFilterPassedCount")
                        .HasColumnType("integer")
                        .HasColumnName("hard_filter_passed_count");

                    b.Property<string>("JobDocumentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_document_hash");

                    b.Property<string>("JobRequisitionCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_requisition_code_snapshot");

                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<string>("JobTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("job_title_snapshot");

                    b.Property<string>("RerankerModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reranker_model_name");

                    b.Property<string>("RetentionFeatureSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("retention_feature_schema_version");

                    b.Property<string>("RetentionModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("retention_model_name");

                    b.Property<int>("RetrievalTopN")
                        .HasColumnType("integer")
                        .HasColumnName("retrieval_top_n");

                    b.Property<int>("RetrievedCandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("retrieved_candidate_count");

                    b.HasKey("Id");

                    b.HasIndex("JobRequisitionId", "ExecutedAtUtc");

                    b.ToTable("job_matching_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_matching_runs_counts_non_negative", "candidate_pool_count >= 0 AND hard_filter_passed_count >= 0 AND retrieved_candidate_count >= 0 AND final_candidate_count >= 0");

                            t.HasCheckConstraint("ck_job_matching_runs_top_n_positive", "retrieval_top_n > 0 AND final_top_n > 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobMatchingRunResult", b =>
                {
                    b.Property<Guid>("JobMatchingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_matching_run_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("CandidateCodeSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("candidate_code_snapshot");

                    b.Property<string>("CandidateDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("candidate_display_name_snapshot");

                    b.Property<double>("CrossEncoderRawScore")
                        .HasColumnType("double precision")
                        .HasColumnName("cross_encoder_raw_score");

                    b.Property<double>("EmbeddingScore")
                        .HasColumnType("double precision")
                        .HasColumnName("embedding_score");

                    b.Property<int>("FinalRank")
                        .HasColumnType("integer")
                        .HasColumnName("final_rank");

                    b.Property<double>("JobFitScore")
                        .HasColumnType("double precision")
                        .HasColumnName("job_fit_score");

                    b.Property<int?>("LongestPreviousJobMonthsSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("longest_previous_job_months_snapshot");

                    b.Property<decimal>("MandatorySkillCoverage")
                        .HasColumnType("numeric")
                        .HasColumnName("mandatory_skill_coverage");

                    b.Property<decimal>("PreferredSkillCoverage")
                        .HasColumnType("numeric")
                        .HasColumnName("preferred_skill_coverage");

                    b.Property<int?>("RetentionLabel")
                        .HasColumnType("integer")
                        .HasColumnName("retention_label");

                    b.Property<int>("RetentionPredictionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("retention_prediction_status");

                    b.Property<int?>("ShortestPreviousJobMonthsSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("shortest_previous_job_months_snapshot");

                    b.Property<int>("SkillTier")
                        .HasColumnType("integer")
                        .HasColumnName("skill_tier");

                    b.HasKey("JobMatchingRunId", "CandidateId");

                    b.HasIndex("JobMatchingRunId", "FinalRank")
                        .IsUnique();

                    b.ToTable("job_matching_run_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_matching_run_results_coverage_range", "mandatory_skill_coverage >= 0 AND mandatory_skill_coverage <= 1 AND preferred_skill_coverage >= 0 AND preferred_skill_coverage <= 1");

                            t.HasCheckConstraint("ck_job_matching_run_results_months_non_negative", "(shortest_previous_job_months_snapshot IS NULL OR shortest_previous_job_months_snapshot >= 0) AND (longest_previous_job_months_snapshot IS NULL OR longest_previous_job_months_snapshot >= 0)");

                            t.HasCheckConstraint("ck_job_matching_run_results_rank_tier_positive", "final_rank > 0 AND skill_tier > 0");

                            t.HasCheckConstraint("ck_job_matching_run_results_retention_label_valid", "retention_label IS NULL OR retention_label IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_job_matching_run_results_retention_status_valid", "retention_prediction_status IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_job_matching_run_results_shortest_lte_longest", "shortest_previous_job_months_snapshot IS NULL OR longest_previous_job_months_snapshot IS NULL OR shortest_previous_job_months_snapshot <= longest_previous_job_months_snapshot");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("JobRequisitionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("job_requisition_status");

                    b.Property<decimal?>("MandatorySkillCoverageThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("mandatory_skill_coverage_threshold");

                    b.Property<int?>("MinimumEducationLevel")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_education_level");

                    b.Property<int?>("MinimumRelevantExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_relevant_experience_months");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date")
                        .HasColumnName("opened_at");

                    b.Property<int>("OpeningsCount")
                        .HasColumnType("integer")
                        .HasColumnName("openings_count");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<string>("RequisitionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requisition_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<bool>("WorkModeHardFilterEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("work_mode_hard_filter_enabled");

                    b.Property<Guid?>("WorkModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_mode_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RequisitionCode")
                        .IsUnique();

                    b.HasIndex("WorkModeId");

                    b.ToTable("job_requisitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_requisitions_closed_at_not_before_opened_at", "closed_at IS NULL OR closed_at >= opened_at");

                            t.HasCheckConstraint("ck_job_requisitions_mandatory_skill_threshold", "mandatory_skill_coverage_threshold IS NULL OR (mandatory_skill_coverage_threshold >= 0 AND mandatory_skill_coverage_threshold <= 1)");

                            t.HasCheckConstraint("ck_job_requisitions_min_relevant_experience", "minimum_relevant_experience_months IS NULL OR minimum_relevant_experience_months >= 0");

                            t.HasCheckConstraint("ck_job_requisitions_openings_count", "openings_count > 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisitionRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<int?>("MinimumExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_experience_months");

                    b.Property<int?>("MinimumProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_proficiency_level");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("JobRequisitionId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("job_requisition_requirements", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_requisition_requirements_min_exp_months_non_negative", "minimum_experience_months IS NULL OR minimum_experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("anonymous_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousCode")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_id");

                    b.Property<string>("CredentialCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credential_code");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("PersonId", "CertificateId");

                    b.ToTable("person_certificates", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_certificates_expiration_date_not_before_issue_date", "issue_date IS NULL OR expiration_date IS NULL OR expiration_date >= issue_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCompetency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_id");

                    b.Property<int?>("ExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("experience_months");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("PersonId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("person_competencies", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_competencies_experience_months_non_negative", "experience_months IS NULL OR experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsNative")
                        .HasColumnType("boolean")
                        .HasColumnName("is_native");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PersonId", "LanguageId")
                        .IsUnique();

                    b.ToTable("person_languages", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonPriorPositionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ImportRowId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_row_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ImportRowId");

                    b.HasIndex("PersonId", "SequenceNumber", "Title")
                        .IsUnique();

                    b.ToTable("person_prior_position_evidences", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_prior_position_evidences_sequence_number_positive", "sequence_number > 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("person_projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_projects_end_date_not_before_start_date", "start_date IS NULL OR end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonSectorExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("experience_months");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("PersonId", "SectorId")
                        .IsUnique();

                    b.ToTable("person_sector_experiences", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_sector_experiences_experience_months_non_negative", "experience_months IS NULL OR experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonWorkModeExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("experience_months");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("WorkModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_mode_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkModeId");

                    b.HasIndex("PersonId", "WorkModeId")
                        .IsUnique();

                    b.ToTable("person_work_mode_experiences", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_work_mode_experiences_experience_months_non_negative", "experience_months IS NULL OR experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.WorkMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("work_modes", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Infrastructure.Persistence.Embeddings.CandidateEmbedding", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_hash");

                    b.Property<Vector>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding_vector");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("CandidateId");

                    b.ToTable("candidate_embeddings", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Infrastructure.Persistence.Embeddings.JobRequisitionEmbedding", b =>
                {
                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_hash");

                    b.Property<Vector>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding_vector");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("JobRequisitionId");

                    b.ToTable("job_requisition_embeddings", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithOne("Candidate")
                        .HasForeignKey("HrDecisionSupport.Domain.Entities.Candidate", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateCareerFeatureSnapshot", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Candidate", "Candidate")
                        .WithMany("CareerFeatureSnapshots")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateEvaluationCase", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Candidate", "Candidate")
                        .WithMany("EvaluationCases")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.JobRequisition", "JobRequisition")
                        .WithMany("CandidateEvaluationCases")
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateWorkModePreference", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Candidate", "Candidate")
                        .WithMany("WorkModePreferences")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.WorkMode", "WorkMode")
                        .WithMany("CandidateWorkModePreferences")
                        .HasForeignKey("WorkModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("WorkMode");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EducationRecord", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("EducationRecords")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Employee", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("HrDecisionSupport.Domain.Entities.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeAssignment", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Department", "Department")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Position", "Position")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeCareerFeatureSnapshot", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Employee", "Employee")
                        .WithMany("CareerFeatureSnapshots")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.EmployeeImportBatch", "ImportBatch")
                        .WithMany("FeatureSnapshots")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeImportRow", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Employee", "Employee")
                        .WithMany("ImportRows")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HrDecisionSupport.Domain.Entities.EmployeeImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeRetentionLabel", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.EmployeeCareerFeatureSnapshot", "EmployeeCareerFeatureSnapshot")
                        .WithOne("RetentionLabel")
                        .HasForeignKey("HrDecisionSupport.Domain.Entities.EmployeeRetentionLabel", "EmployeeCareerFeatureSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeCareerFeatureSnapshot");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmploymentHistory", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("EmploymentHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobLanguageRequirement", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.JobRequisition", "JobRequisition")
                        .WithMany("LanguageRequirements")
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRequisition");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobMatchingRun", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.JobRequisition", "JobRequisition")
                        .WithMany()
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobMatchingRunResult", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.JobMatchingRun", "JobMatchingRun")
                        .WithMany("Results")
                        .HasForeignKey("JobMatchingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobMatchingRun");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisition", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Department", "Department")
                        .WithMany("JobRequisitions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Position", "Position")
                        .WithMany("JobRequisitions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.WorkMode", "WorkMode")
                        .WithMany()
                        .HasForeignKey("WorkModeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("WorkMode");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisitionRequirement", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Competency", "Competency")
                        .WithMany("JobRequisitionRequirements")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.JobRequisition", "JobRequisition")
                        .WithMany("Requirements")
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCertificate", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Certificate", "Certificate")
                        .WithMany("PersonCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonCertificates")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCompetency", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Competency", "Competency")
                        .WithMany("PersonCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonCompetencies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonLanguage", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Language", "Language")
                        .WithMany("PersonLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonLanguages")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonPriorPositionEvidence", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.EmployeeImportRow", "ImportRow")
                        .WithMany("PriorPositionEvidences")
                        .HasForeignKey("ImportRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PriorPositionEvidences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportRow");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonProject", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonProjects")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Project", "Project")
                        .WithMany("PersonProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonSectorExperience", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonSectorExperiences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Sector", "Sector")
                        .WithMany("PersonSectorExperiences")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonWorkModeExperience", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonWorkModeExperiences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.WorkMode", "WorkMode")
                        .WithMany("PersonWorkModeExperiences")
                        .HasForeignKey("WorkModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("WorkMode");
                });

            modelBuilder.Entity("HrDecisionSupport.Infrastructure.Persistence.Embeddings.CandidateEmbedding", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Candidate", null)
                        .WithOne()
                        .HasForeignKey("HrDecisionSupport.Infrastructure.Persistence.Embeddings.CandidateEmbedding", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrDecisionSupport.Infrastructure.Persistence.Embeddings.JobRequisitionEmbedding", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.JobRequisition", null)
                        .WithOne()
                        .HasForeignKey("HrDecisionSupport.Infrastructure.Persistence.Embeddings.JobRequisitionEmbedding", "JobRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("CareerFeatureSnapshots");

                    b.Navigation("EvaluationCases");

                    b.Navigation("WorkModePreferences");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("PersonCertificates");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Competency", b =>
                {
                    b.Navigation("JobRequisitionRequirements");

                    b.Navigation("PersonCompetencies");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Department", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("JobRequisitions");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CareerFeatureSnapshots");

                    b.Navigation("ImportRows");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeCareerFeatureSnapshot", b =>
                {
                    b.Navigation("RetentionLabel");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeImportBatch", b =>
                {
                    b.Navigation("FeatureSnapshots");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeImportRow", b =>
                {
                    b.Navigation("PriorPositionEvidences");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobMatchingRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisition", b =>
                {
                    b.Navigation("CandidateEvaluationCases");

                    b.Navigation("LanguageRequirements");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Language", b =>
                {
                    b.Navigation("PersonLanguages");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Person", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("EducationRecords");

                    b.Navigation("Employee");

                    b.Navigation("EmploymentHistories");

                    b.Navigation("PersonCertificates");

                    b.Navigation("PersonCompetencies");

                    b.Navigation("PersonLanguages");

                    b.Navigation("PersonProjects");

                    b.Navigation("PersonSectorExperiences");

                    b.Navigation("PersonWorkModeExperiences");

                    b.Navigation("PriorPositionEvidences");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Position", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("JobRequisitions");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Project", b =>
                {
                    b.Navigation("PersonProjects");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Sector", b =>
                {
                    b.Navigation("PersonSectorExperiences");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.WorkMode", b =>
                {
                    b.Navigation("CandidateWorkModePreferences");

                    b.Navigation("PersonWorkModeExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
