// <auto-generated />
using System;
using HrDecisionSupport.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HrDecisionSupport.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrDecisionSupportDbContext))]
    partial class HrDecisionSupportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CandidateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("candidate_code");

                    b.Property<int>("CandidateSource")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_source");

                    b.Property<string>("ExternalCandidateId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_candidate_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCode")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateEvaluationCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("JobRequisitionId");

                    b.HasIndex("CandidateId", "JobRequisitionId")
                        .IsUnique();

                    b.ToTable("candidate_evaluation_cases", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Issuer")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("CompetencyCategory")
                        .HasColumnType("integer")
                        .HasColumnName("competency_category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("competencies", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EducationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DegreeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("degree_level");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_of_study");

                    b.Property<DateOnly?>("GraduationDate")
                        .HasColumnType("date")
                        .HasColumnName("graduation_date");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("institution");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("education_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_education_records_graduation_date_not_before_start_date", "start_date IS NULL OR graduation_date IS NULL OR graduation_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("employment_status");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("termination_date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("employees", null, t =>
                        {
                            t.HasCheckConstraint("ck_employees_termination_date_not_before_hire_date", "termination_date IS NULL OR termination_date >= hire_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PositionId");

                    b.ToTable("employee_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_assignments_end_date_not_before_start_date", "end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmploymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employer_name");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position_title");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("employment_histories", null, t =>
                        {
                            t.HasCheckConstraint("ck_employment_histories_end_date_not_before_start_date", "end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("JobRequisitionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("job_requisition_status");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date")
                        .HasColumnName("opened_at");

                    b.Property<int>("OpeningsCount")
                        .HasColumnType("integer")
                        .HasColumnName("openings_count");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<string>("RequisitionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requisition_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RequisitionCode")
                        .IsUnique();

                    b.ToTable("job_requisitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_requisitions_closed_at_not_before_opened_at", "closed_at IS NULL OR closed_at >= opened_at");

                            t.HasCheckConstraint("ck_job_requisitions_openings_count", "openings_count > 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisitionRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<int?>("MinimumExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_experience_months");

                    b.Property<int?>("MinimumProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_proficiency_level");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("JobRequisitionId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("job_requisition_requirements", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_requisition_requirements_min_exp_months_non_negative", "minimum_experience_months IS NULL OR minimum_experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("anonymous_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousCode")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_id");

                    b.Property<string>("CredentialCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credential_code");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("PersonId", "CertificateId");

                    b.ToTable("person_certificates", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_certificates_expiration_date_not_before_issue_date", "issue_date IS NULL OR expiration_date IS NULL OR expiration_date >= issue_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCompetency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_id");

                    b.Property<int?>("ExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("experience_months");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("PersonId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("person_competencies", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_competencies_experience_months_non_negative", "experience_months IS NULL OR experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsNative")
                        .HasColumnType("boolean")
                        .HasColumnName("is_native");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PersonId", "LanguageId")
                        .IsUnique();

                    b.ToTable("person_languages", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("person_projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_projects_end_date_not_before_start_date", "start_date IS NULL OR end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonSectorExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("experience_months");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("PersonId", "SectorId")
                        .IsUnique();

                    b.ToTable("person_sector_experiences", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_sector_experiences_experience_months_non_negative", "experience_months IS NULL OR experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonWorkModeExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ExperienceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("experience_months");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("WorkModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_mode_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkModeId");

                    b.HasIndex("PersonId", "WorkModeId")
                        .IsUnique();

                    b.ToTable("person_work_mode_experiences", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_work_mode_experiences_experience_months_non_negative", "experience_months IS NULL OR experience_months >= 0");
                        });
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.WorkMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("work_modes", (string)null);
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithOne("Candidate")
                        .HasForeignKey("HrDecisionSupport.Domain.Entities.Candidate", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.CandidateEvaluationCase", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Candidate", "Candidate")
                        .WithMany("EvaluationCases")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.JobRequisition", "JobRequisition")
                        .WithMany("CandidateEvaluationCases")
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EducationRecord", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("EducationRecords")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Employee", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("HrDecisionSupport.Domain.Entities.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmployeeAssignment", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Department", "Department")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Position", "Position")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.EmploymentHistory", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("EmploymentHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisition", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Department", "Department")
                        .WithMany("JobRequisitions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Position", "Position")
                        .WithMany("JobRequisitions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisitionRequirement", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Competency", "Competency")
                        .WithMany("JobRequisitionRequirements")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.JobRequisition", "JobRequisition")
                        .WithMany("Requirements")
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCertificate", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Certificate", "Certificate")
                        .WithMany("PersonCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonCertificates")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonCompetency", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Competency", "Competency")
                        .WithMany("PersonCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonCompetencies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonLanguage", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Language", "Language")
                        .WithMany("PersonLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonLanguages")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonProject", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonProjects")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Project", "Project")
                        .WithMany("PersonProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonSectorExperience", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonSectorExperiences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.Sector", "Sector")
                        .WithMany("PersonSectorExperiences")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.PersonWorkModeExperience", b =>
                {
                    b.HasOne("HrDecisionSupport.Domain.Entities.Person", "Person")
                        .WithMany("PersonWorkModeExperiences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDecisionSupport.Domain.Entities.WorkMode", "WorkMode")
                        .WithMany("PersonWorkModeExperiences")
                        .HasForeignKey("WorkModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("WorkMode");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("EvaluationCases");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("PersonCertificates");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Competency", b =>
                {
                    b.Navigation("JobRequisitionRequirements");

                    b.Navigation("PersonCompetencies");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Department", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("JobRequisitions");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.JobRequisition", b =>
                {
                    b.Navigation("CandidateEvaluationCases");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Language", b =>
                {
                    b.Navigation("PersonLanguages");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Person", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("EducationRecords");

                    b.Navigation("Employee");

                    b.Navigation("EmploymentHistories");

                    b.Navigation("PersonCertificates");

                    b.Navigation("PersonCompetencies");

                    b.Navigation("PersonLanguages");

                    b.Navigation("PersonProjects");

                    b.Navigation("PersonSectorExperiences");

                    b.Navigation("PersonWorkModeExperiences");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Position", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("JobRequisitions");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Project", b =>
                {
                    b.Navigation("PersonProjects");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.Sector", b =>
                {
                    b.Navigation("PersonSectorExperiences");
                });

            modelBuilder.Entity("HrDecisionSupport.Domain.Entities.WorkMode", b =>
                {
                    b.Navigation("PersonWorkModeExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
